import {sourceIdentifier} from '../part-identity.js?v=purchase-1';
const identifierText=p=>{const id=sourceIdentifier(p,qualifiedOffers(p)[0]);return id.value==='Not verified'?`Selection ID: ${p.id}`:`${id.label}: ${id.value}`};
import {el,labels,money,machineData,renderCommerce,referenceCost,readSaved,updateSaved,download,external,safeUrl,safeInspectionUrl,isVerifiedOffer,offerTitle,retailerLabel,isModelUnit,modelShapeCount,isIdentificationRequest,qualifiedOffers,requestKind,readMachineNotes,writeMachineNotes,downloadText,machineSupport,supportNavigation,selectionSummary,buildPartsRequest,replacementAction} from './commerce.js?v=purchase-1';
const $=id=>document.getElementById(id),savedPage=location.pathname.includes('/saved/');
let catalog,parts=[],selected=null,page=0,mode='equipment';const size=50;
function counter(){const n=readSaved().reduce((sum,x)=>sum+x.quantity,0);$('saved-count').textContent=n}
addEventListener('saved-parts-change',()=>{counter();if(savedPage)renderSaved()});counter();
function geometryLabel(s){return /reconstructed|study/i.test(s??'')?'Reconstructed study · part identities incomplete':s}
function categories(){for(const v of [...new Set(catalog.machines.map(m=>m.category))].sort()){const option=el('option',v);option.value=v;$('category').append(option)}for(const m of catalog.machines){const option=el('option',m.title);option.value=m.id;$('machine').append(option)}}
function filter(){const q=$('search').value.trim().toLowerCase(),cat=$('category').value,machine=$('machine').value,status=$('availability').value;const ids=new Set(catalog.machines.filter(m=>(cat==='all'||m.category===cat)&&(machine==='all'||m.id===machine)).map(m=>m.id));return parts.filter(p=>ids.has(p.machineId)&&(status==='all'||(status==='missing'?p.status!=='verified-product':p.status===status))&&`${p.name} ${p.id} ${p.assembly} ${p.partNumber??''} ${p.sku??''} ${catalog.machines.find(m=>m.id===p.machineId)?.title}`.toLowerCase().includes(q))}
function renderEquipment(){const q=$('search').value.trim().toLowerCase(),cat=$('category').value,machine=$('machine').value,status=$('availability').value;const list=catalog.machines.filter(m=>(cat==='all'||m.category===cat)&&(machine==='all'||m.id===machine)&&`${m.title} ${m.category} ${m.id}`.toLowerCase().includes(q)&&(status==='all'||(status==='verified-product'?m.sales>0:m.parts>m.sales)));const grid=$('equipment-grid');grid.replaceChildren();for(const m of list){const a=el('a',null,'equipment-card');a.href=m.route;if(m.image){const img=el('img');img.src=m.image;img.alt=`${m.title} source view`;img.loading='lazy';a.append(img)}else a.append(el('div',m.id==='farmbot'?'GENESIS / v1.8':m.title,'empty-art'));const body=el('div',null,'card-body');body.append(el('span',m.category,'number'),el('h2',m.title),el('span',geometryLabel(m.geometryStatus),'geometry-label'),el('p',`${m.parts.toLocaleString()} listed components · ${m.sales} verified sales links`),el('p',`${m.prices} priced entries · ${m.parts-m.sales} sales links still needed`));a.append(body);grid.append(a)}$('results').textContent=`${list.length} equipment pages`;if(!list.length)grid.append(el('p','No equipment matches. Clear the search or filters.'))}
async function inspect(row){selected=row;const machine=catalog.machines.find(m=>m.id===row.machineId);const panel=$('part-panel');panel.replaceChildren(el('p',machine.title,'eyebrow'),el('h2',row.name),el('p',row.id,'commerce-note'),el('p',row.assembly,'commerce-note'),el('p','Loading retailer details…','commerce-note'));panel.scrollIntoView({block:'nearest'});try{const data=await machineData(row.machineId),p=data.parts.find(p=>p.id===row.id);if(selected!==row)return;panel.replaceChildren(el('p',machine.title,'eyebrow'),el('h2',p.name),el('p',identifierText(p),'commerce-note'),el('p',`Documented quantity: ${p.quantity??'unknown'}`,'commerce-note'),renderCommerce({...data,route:machine.route},p));const view=el('a','Inspect on the equipment page');view.href=`${machine.route}?part=${encodeURIComponent(p.id)}`;panel.append(view);if(p.sourceUrl)panel.append(el('p'),external('Part documentation',p.sourceUrl));panel.tabIndex=-1;panel.focus({preventScroll:true})}catch(error){panel.append(el('p',`${error.message}. Select again to retry.`))}renderParts()}
function renderParts(){const list=filter(),pages=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,pages-1);$('parts-body').replaceChildren();for(const p of list.slice(page*size,(page+1)*size)){const tr=el('tr');tr.dataset.selected=String(selected?.id===p.id&&selected?.machineId===p.machineId);const name=el('td'),b=el('button',p.name);b.onclick=()=>inspect(p);name.append(b,el('small',p.partNumber??p.sku??p.id));const machine=el('td',catalog.machines.find(m=>m.id===p.machineId).title),status=el('td',labels[p.status],'sale-status '+p.status),value=el('td',money(p.value));tr.append(name,machine,status,value);$('parts-body').append(tr)}$('results').textContent=`${list.length.toLocaleString()} of ${parts.length.toLocaleString()} components`;$('page-count').textContent=`Page ${page+1} of ${pages}`;$('previous').disabled=page===0;$('next').disabled=page>=pages-1;$('empty-parts').hidden=list.length!==0}
function render(){if(mode==='equipment')renderEquipment();else renderParts()}
function switchMode(next){mode=next;page=0;$('equipment-grid').hidden=next!=='equipment';$('parts-workspace').hidden=next!=='parts';$('tab-equipment').setAttribute('aria-selected',String(next==='equipment'));$('tab-parts').setAttribute('aria-selected',String(next==='parts'));$('search').placeholder=next==='equipment'?'Find your equipment…':'Search all parts, assemblies or part numbers…';render()}
function textValue(value){return typeof value==='string'?value:JSON.stringify(value)}
function savedIdentity(body,item){
 const visual=isModelUnit(item),count=modelShapeCount(item);
 if(visual){body.append(el('p','Reconstructed visual unit · OEM part identity unverified','compatibility-note'));if(count!==null)body.append(el('p',`${count} model shape${count===1?'':'s'} · documented part quantity unknown`,'commerce-note'))}
 body.append(el('p',`Selection ID: ${item.id}`,'commerce-note'),el('p',`Machine revision: ${item.machineRevision??item.revision??'unknown'}`,'commerce-note'),el('p',`Part revision: ${item.partRevision??'unknown'}`,'commerce-note'),el('p',`Documented source quantity: ${item.sourceQuantity??'unknown'}`,'commerce-note'));
 if(item.machineConfiguration){const config=el('details',null,'offer-details');config.append(el('summary','Documented machine configuration'),el('p',textValue(item.machineConfiguration),'commerce-note'));body.append(config)}
 if(item.assembly)body.append(el('p',`Assembly: ${item.assembly}`,'commerce-note'));
 body.append(el('p',identifierText(item),'commerce-note'));
 const publication=[item.publication?`Publication ${item.publication}`:null,(item.pvc??item.PVC)?`PVC ${item.pvc??item.PVC}`:null,Array.isArray(item.sourcePages)&&item.sourcePages.length?`Source pages ${item.sourcePages.join(', ')}`:null].filter(Boolean);
 if(publication.length)body.append(el('p',publication.join(' · '),'commerce-note'));
 if(item.quantityBasis)body.append(el('p',item.quantityBasis,'commerce-note'));
 for(const [key,value] of Object.entries(item)){if(/serial|option/i.test(key)&&value!=null)body.append(el('p',`${key}: ${textValue(value)}`,'compatibility-note'))}
 if(item.geometryAssociation)body.append(el('p',textValue(item.geometryAssociation),'compatibility-note'));
 if(item.modelSourceSha256){const source=el('details',null,'offer-details');source.append(el('summary','Reconstructed model source'),el('p',`SHA-256 ${item.modelSourceSha256}`,'commerce-note'));if(item.sourceMembers)source.append(el('p',`Source members: ${item.sourceMembers.join(', ')}`,'commerce-note'));body.append(source)}
}
function renderMachineContext(list){
 const container=$('machine-context');container.replaceChildren();const notes=readMachineNotes(),machines=new Map(list.map(item=>[item.machineId,item]));
 if(!machines.size)return;
 container.append(el('h2','Your machine details'),el('p','Add the serial number and installed options to your parts request. These notes stay in this browser and do not verify fit.','commerce-note'));
 for(const [id,item] of machines){const fieldset=el('fieldset',null,'machine-context-card'),legend=el('legend',item.machineTitle??id),serial=el('input'),config=el('textarea'),status=el('p','Saved locally as you type.','commerce-note');
  const stored=Object.hasOwn(notes,id)?notes[id]:{};serial.type='text';serial.maxLength=200;serial.autocomplete='off';serial.value=stored?.serialNumber??'';config.rows=3;config.maxLength=4000;config.value=stored?.configurationNotes??'';
  const serialLabel=el('label','Machine serial number'),configLabel=el('label','Installed options / configuration / request notes');serialLabel.append(serial);configLabel.append(config);status.setAttribute('role','status');
  const save=()=>{status.textContent=writeMachineNotes(id,{serialNumber:serial.value,configurationNotes:config.value})?'Saved in this browser.':'Storage unavailable. Copy your notes before leaving.'};serial.oninput=save;config.oninput=save;fieldset.append(legend,serialLabel,configLabel,status);container.append(fieldset);
 }
}
function renderSaved(){
 const list=readSaved(),container=$('saved-list');container.replaceChildren();renderMachineContext(list);const totals=new Map(),groups=selectionSummary(list);let unknown=0;
 const summary=$('selection-summary');summary.replaceChildren(el('h2','Next steps'),el('p',`${groups.retailerLinked.length} selection${groups.retailerLinked.length===1?'':'s'} with product references · ${groups.requests.length} identification or quote request${groups.requests.length===1?'':'s'}`),el('p','Open a retailer for a listed product, or download a request with your machine details and source references. No request is sent automatically.','commerce-note'));
 for(const [heading,entries] of [['Selections with product references',groups.retailerLinked],['Identification / quote requests',groups.requests]]){
  const section=el('section',null,'saved-group');section.append(el('h2',`${heading} (${entries.length})`));if(!entries.length)section.append(el('p','No saved selections in this group.','commerce-note'));container.append(section);
  for(const item of entries){
   const visual=isIdentificationRequest(item),c=item.commerce??{},qualified=qualifiedOffers(item),action=replacementAction(item),row=el('article',null,'saved-row'),body=el('div'),qty=el('label',visual?'Requested selections':'Quantity'),input=el('input'),actions=el('div',null,'actions');
   body.append(el('p',item.machineTitle,'eyebrow'),el('h3',item.name),el('p',identifierText(item),'commerce-note'));const identity=el('details',null,'offer-details');identity.append(el('summary','Part identity & source'));savedIdentity(identity,item);body.append(el('p',`${labels[c.salesStatus]??'Needs verification'} · ${visual?'Price unavailable':money(c.value)}`),identity);const fit=el('details',null,'offer-details');fit.append(el('summary','Fit, availability & price notes'),el('p',Array.isArray(c.notes)?c.notes.join(' '):c.notes??'','commerce-note'));body.append(fit);if(qualified.length)body.append(el('p','Confirm the machine serial, installed part and current stock with the retailer.','compatibility-note'));
   if(visual)body.append(el('p','Identify the physical part and confirm its quantity before ordering.','compatibility-note'));
   input.type='number';input.min=1;input.max=9999;input.step=1;input.value=item.quantity;input.setAttribute('aria-label',`${visual?'Requested selections':'Quantity'} for ${item.name}`);input.onchange=()=>updateSaved(item.machineId,item.id,input.value);qty.append(input);
   body.append(el('p',action.notice,'compatibility-note'));
   if(!action.ready){const confirm=el('button',action.label,'retailer-button');confirm.type='button';confirm.onclick=()=>{const input=$('machine-context').querySelector('input');$('machine-context').scrollIntoView({block:'start'});input?.focus({preventScroll:true})};actions.append(confirm,el('p','Add your machine details above, then download and share the request. Nothing is sent automatically.','commerce-note'));}
   const inspection=safeInspectionUrl(item.inspectionUrl);if(inspection){const inspect=el('a','Inspect on equipment');inspect.href=inspection;actions.append(inspect)}
   for(const offer of c.offers??[]){if(!safeUrl(offer?.url))continue;const verified=action.offers.includes(offer),reference=qualified.includes(offer);actions.append(external(verified?retailerLabel(offer):reference?`${retailerLabel(offer)} · reference only`:`${offer.alternative?'Alternative product reference':'Unverified supplier reference'} · ${offerTitle(offer)}`,offer.url,verified?'retailer-button':'reference-link'))}
   for(const offer of c.candidateOffers??[]){if(safeUrl(offer?.url))actions.append(external(`Unverified candidate retailer reference · ${offerTitle(offer)}`,offer.url,'reference-link'))}
   for(const link of c.supportLinks??[]){if(safeUrl(link?.url))actions.append(external(`${link.label??'Dealer or source reference'} · reference navigation`,link.url,'reference-link'))}
   actions.append(supportNavigation(item.machineId));
   if(item.sourceUrl&&safeUrl(item.sourceUrl))actions.append(external('Source documentation',item.sourceUrl,'reference-link'));
   const remove=el('button','Remove');remove.onclick=()=>updateSaved(item.machineId,item.id,0);actions.append(remove);row.append(body,qty,actions);section.append(row);
   const cost=referenceCost(item);fit.append(el('p',c.value?.basis??'','commerce-note'));
   if(cost){body.append(el('p',`Reference cost: ${money(cost)} · ${cost.note??''}`,'commerce-note'));totals.set(cost.currency,(totals.get(cost.currency)??0)+cost.amount)}else unknown++;
   if(c.fitNeedsReview)body.append(el('p','Variant or compatibility needs review','compatibility-note'));
   if(c.alternative)body.append(el('p','Source example / alternative; not a required additional part','compatibility-note'));
   for(const offer of [...(c.offers??[]),...(c.candidateOffers??[])]){if(offer.compatibility)fit.append(el('p',typeof offer.compatibility==='string'?offer.compatibility:offer.compatibility.detail??JSON.stringify(offer.compatibility),'compatibility-note'));const stock=offer.availability??offer.availabilityStatus??offer.stockStatus??offer.stock;if(stock)fit.append(el('p',`Availability at check: ${textValue(stock)}`,'commerce-note'));if(offer.checkedAt)fit.append(el('p',`Checked ${new Date(offer.checkedAt).toLocaleDateString()}. Confirm price, stock and fit with the retailer.`,'commerce-note'))}
  }
 }
 const total=$('totals');total.replaceChildren(el('h2','Retailer reference subtotal'));for(const [currency,amount]of totals)total.append(el('p',money({amount,currency})));
 total.append(el('p',`${unknown} selected component types have no verified exact-part value. They are excluded from the subtotal.`,'commerce-note'),el('p','Known pack sizes are rounded up to whole packs. Quantities for pairs, spools and assemblies use the value basis shown with each entry. This is a sourcing reference, not a complete machine quote. Pack sizes, cut lengths, fit, tax, shipping and current availability must be confirmed.','commerce-note'));
 $('empty-saved').hidden=list.length>0;for(const id of ['export-saved','export-gaps','export-request'])$(id).disabled=!list.length;$('saved-status').textContent=`${list.length} saved component types. Product references open the supplier’s site; fit requires confirmation. No order is placed here.`;
}
async function savedExport(){const items=readSaved(),ids=[...new Set(items.map(item=>item.machineId))],notes=readMachineNotes(),support=Object.fromEntries((await Promise.all(ids.map(async id=>[id,await machineSupport(id)]))).filter(([,value])=>value));return {exportedAt:new Date().toISOString(),status:'Prepared locally; no request or order submitted',machineContext:Object.fromEntries(ids.map(id=>[id,{...(Object.hasOwn(notes,id)?notes[id]:{}),userSupplied:true,fitVerified:false}])),machineSupport:support,items}}
async function exportSelection(kind){const data=await savedExport();if(kind==='text')downloadText('equipment-parts-request.txt',buildPartsRequest(data.items,data.machineContext,data.machineSupport,{exportedAt:data.exportedAt,origin:location.origin}));else if(kind==='gaps')download('equipment-missing-part-details.json',{...data,items:data.items.filter(x=>!replacementAction(x).ready||x.commerce?.value?.amount==null||x.commerce?.fitNeedsReview||x.commerce?.alternative)});else download('equipment-parts-selection.json',data)}

async function start(){try{if(savedPage){renderSaved();$('export-saved').onclick=()=>exportSelection('json');$('export-gaps').onclick=()=>exportSelection('gaps');$('export-request').onclick=()=>exportSelection('text');window.equipmentShop={renderSaved,savedExport,buildPartsRequest};return}catalog=await fetch('/shop/catalog.json').then(r=>{if(!r.ok)throw Error('Equipment directory unavailable');return r.json()});categories();$('machine-total').textContent=catalog.machines.length;$('part-total').textContent=catalog.parts.toLocaleString();$('sale-total').textContent=catalog.verifiedSalesPages;$('price-total').textContent=catalog.verifiedValues;renderEquipment();parts=(await Promise.all(catalog.indexChunks.map(u=>fetch(u).then(r=>{if(!r.ok)throw Error('Part index unavailable');return r.json()})))).flat();$('tab-parts').disabled=false;$('tab-equipment').onclick=()=>switchMode('equipment');$('tab-parts').onclick=()=>switchMode('parts');for(const id of ['search','category','machine','availability'])$(id).addEventListener(id==='search'?'input':'change',()=>{page=0;render()});$('previous').onclick=()=>{page--;renderParts()};$('next').onclick=()=>{page++;renderParts()};$('export-coverage').onclick=()=>download('equipment-coverage.json',catalog);const params=new URLSearchParams(location.search),requestedMachine=params.get('machine'),requestedStatus=params.get('availability');if(catalog.machines.some(m=>m.id===requestedMachine))$('machine').value=requestedMachine;if([...$('availability').options].some(option=>option.value===requestedStatus))$('availability').value=requestedStatus;if(params.get('q'))$('search').value=params.get('q');if(params.get('mode')==='parts'||params.get('q'))switchMode('parts');else render();window.equipmentShop={catalog,parts,inspect,switchMode};}catch(error){$('results').textContent=error.message+'. Reload to retry.'}}
start();
